### ISSUE TITLE
ImportError: cannot import name Client

### ISSUE THREAD

**Issue by tdesroches** [FreeOpcUa/python-opcua#524]
Since upgrading to 0.90.6 from 0.90.3 I get an import error on "Client" has something changed in the package that could be causing this?  If I revert back to 0.90.3 then everything is fine again.

**Comment by tdesroches** [comment]
Actually this seems to be an issue with the pip3 install.  You can close this I think.
